version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "matteovivona"
    reviewers:
      - "matteovivona"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "alemagio"
    reviewers:
      - "matteovivona"

  - package-ecosystem: npm
    directory: /packages/http
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/main-loader
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/mongodb
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/projection
    schedule:
      interval: daily
